### ISSUE TITLE
observations

### ISSUE THREAD

**Issue by davephillips** [baconpaul/BaconPlugs#1]
Linux Fedora 23
Rack 0.5.1 from source

Hi Paul ! Your plugins look very cool, but performance here is an issue. Each one takes a long time to load, and if I turn a knob my cursor disappears (I have to switch workspace to retrieve it). The slider works fine. Any suggestions for improving the load times and the knob situation ?

**Comment by baconpaul** [comment]
Hi!

First, thanks for trying them!! It was mostly me just screwing around and seeing if I could actually get something working. I’m presuming everyone else’s modules work fine yeah?

As to performance: I’m not sure; I only run them in a VM on Linux, and then rarely. Mostly Mac, where they seem OK. I’ll try and get a time to boot them in my (Ubuntu recent LTS) VM and take a look. The cursor is odd though. I haven’t seen that on MacOS. I wonder if I have some error in my widget hierarchy.

Is there any console output or any such thing? The only thing I’m doing in the load path which is different than any other plug is loading a TTF font from res/. I should also only be doing that once but I’ll check to make sure I didn’t blow it.

Bit busy today but will try to peek. Thanks again for the feedback!

Best

- Paul

On Dec 20, 2017, at 08:19, davephillips <notifications@github.com<mailto:notifications@github.com>> wrote:


Linux Fedora 23
Rack 0.5.1 from source

Hi Paul ! Your plugins look very cool, but performance here is an issue. Each one takes a long time to load, and if I turn a knob my cursor disappears (I have to switch workspace to retrieve it). The slider works fine. Any suggestions for improving the load times and the knob situation ?

**Comment by baconpaul** [comment]
OK I ran it in my VM and with 0.5.1 I'm seeing super high CPU usage even with an empty Rack (as reported by Top) vs Mac. An empty rack (built from 0.5.1 with Fundamental and BaconPlugs built as plugs) shows about 4% CPU on macOS and about 78% on my vm (which is latest ubuntu LTS running in virtual box).

So to figure this out I'm going to need to debug that problem first. Sorry, not sure I'll have a great answer soon, unless the above sounds familiar to you.

**Comment by baconpaul** [comment]
Hey @davephillips in an issue over on the VCVRack main set (https://github.com/VCVRack/Rack/issues/517#issuecomment-354128844) Andrew gave me a hint which has had me find where my overdraws were happening. I don't think I'll get the change pushed before the new year, but there's definitely a problem which leads to what you say, and I have a fix in my dev version now. I'll try and push the branch to GitHub if I can get it working, but won't have time to merge to master and test. Thanks for the report

**Comment by baconpaul** [comment]
Just quickly: I can confirm the frame buffer tip from Andrew does indeed fix an overdraw in my widgets which, while not that big a problem on my mac, would definitely cause what you saw on Linux (and does actually burn CPU on my mac, just not a huge amount).

I won't get a fix until a bit into January in place, but definitely a problem. Thanks for spotting.

**Comment by baconpaul** [comment]
@davephillips I just pushed a new version of "master" which has frame buffering everywhere I can easily do it. (I'd still like to add it for the 7 segment graph thing). My Linux VM has it all build fine and it seems less CPU-y but still I'm not 100% confident that virtual box will represent your setup properly.

But it's definitely the case that the version 3 days ago was drawing fonts thousands of times a second and this version is absolutely not. Same for notches on the slider and stuff. So I'm going to close this issue now, and make a note for myself to get a better linux testing env.

I'll probably do a binary release of these plugs and add them to community sometime this week also. Thanks for your testing.

**Comment by davephillips** [comment]
Hi Paul, Thanks for the note and the new code. :) I've built the plugins for 0.5.x with no troubles, GUI issues are gone. Tests so far are good except for the Glissinator, I'm not sure I'm using it correctly. I get full volume from the input signal if the fader is all the way to the bottom. Moving it upwards just a little cancels the sound entirely. But the other three modules are sweet.
EDIT: Scratch the problem with Glissinator, I saw your example, it works fine. Really cool, in fact. :)

**Comment by baconpaul** [comment]
Hey great. And glad you like it! I wasn't quite sure how to visually represent audio signal space from control voltage space. They are both just signals, but the 1v/octave CV signal has a very different meaning than the output of a VCO. Any ideas welcome!

Thanks for the test! I have pushed a few other improvements in the last couple of hours too. I'll do a proper release (like with a version tag and in the community list) next week sometime, but there's one more plugin I want to add.
