### ISSUE TITLE
PolyGnome v 2.3.1 - BPM sometimes displays lower number than typed-in integer

### ISSUE THREAD

**Issue by John-L-Rose** [baconpaul/BaconPlugs#102]
I first noticed it when I typed in a BPM of 90, and it displayed "089" on the LED.
Other numbers that display a value one less than typed are 36, 37, 45, 47, 48, 52, 56. After that I gave up looking for more. The results are repeatable.
Other integers between those listed display fine.

I _think_ the tempo that appears at the gate output is correct anyway, in the sense of corresponding to the typed-in value, and compared to other clocks on a scope.

Now, if I type in "90.0001" it rounds down to "90" (as shown when you hover the cursor over the knob) and it correctly shows "090" in the LED display.

**Comment by baconpaul** [comment]
Ahh thank you

**Comment by baconpaul** [comment]
Anyway I fixed this just now and submitted a 2.4.0 to the library, along with support for the built in rack dark panel mode as opposed to the hand-rolled dark panel mode in 2.3.1

Thanks for the accurate report. Made it 5 minutes work to find the `(int)` vs `(int)std::round` I had missed :)

**Comment by John-L-Rose** [comment]
Yay! Thanks.

> Thanks for the accurate report.

You're welcome.
As a former shortwave transmitter technician, I was used to making detailed fault reports.
