### ISSUE TITLE
Some praise and a question (Harmonee! Break out some controls!)

### ISSUE THREAD

**Issue by 77377** [baconpaul/BaconPlugs#19]
Hi, love your modules, really do. Your clock foremost makes life so much easier for me. There are many ways to achieve polymeters in vcv rack, not as many capable of creating true polymeters like yours does so effortlessly. The karplus strong implementation sounds awesome already, and I can't wait what you'll do with the other two front knobs. (:

Would it be very difficult to make CV controls for switches on harmonee? I'd like to programmatically change how much I transpose voltage over time?

Cheers!

**Comment by baconpaul** [comment]
Wow thanks! I didn't even know people were using them. 

Not difficult. Just need to find a bit of time. Lemme take a poke.

I have a 0.6.3 in the community queue now which fixes a few bugs after this has been dormant for a bit.

**Comment by baconpaul** [comment]
Hey so turns out this was actually pretty easy to code up. Let me try and sweep it into 0.6.3 release.

**Comment by 77377** [comment]
Oh so awesome! Keep it up! (;

**Comment by baconpaul** [comment]
Just FYI: The rack community team rebuilt plugins today which will update BaconMusic to 0.6.3 and add this feature. Enjoy!
