### ISSUE TITLE
candidate_v1.0.1 build fail windows

### ISSUE THREAD

**Issue by Coirt** [baconpaul/BaconPlugs#27]
```
src/PolyGenerator.hpp:5:10: fatal error: MidiFile.h: No such file or directory
 #include "MidiFile.h"
```
make dep has nothing to do, something missing from the makefile?

**Comment by Coirt** [comment]
release_v1.0.1 is also the same.

**Comment by baconpaul** [comment]
`git submodule update —init —recursive`

I had asked how to make this part of deps here https://community.vcvrack.com/t/plugin-deps-resolution/3704/2 and it doesn’t seem this is something folks put into deps.

**Comment by baconpaul** [comment]
I have updated the readme to indicate this need. I may still add it to `make dep` despite Andrews thought that I should not. Your feedback welcome.

**Comment by baconpaul** [comment]
Anyway I pushed a makefile change which adds this as a dep and runs the submodule init. So `make dep` should check out the code both at master and release_v1.0.1

**Comment by Coirt** [comment]
Sweet, had gotten used to not doing that step in v1.

**Comment by Coirt** [comment]
```
echo "libs/midifile/LICENSE.txt does not exist"
libs/midifile/LICENSE.txt does not exist
echo "executing git submodule update"
executing git submodule update
git submodule update --init --recursive
Submodule 'libs/midifile' (https://github.com/craigsapp/midifile.git) registered for path 'libs/midifile'
Cloning into '/home/Phil/rack-1.1.6/rack/plugins/baconplugs/libs/midifile'...
Submodule path 'libs/midifile': checked out '99e87b684f88ebff6417ef25f269f1a95b780ad2'
make: *** No rule to make target 'j8'.  Stop.

```

On `make dep`

**Comment by baconpaul** [comment]
What's the command line you are running?

**Comment by Coirt** [comment]
Just `make dep -j8` submodule update doesn't do anything but `make` builds

**Comment by baconpaul** [comment]
"-j8" needs a space. "-j 8" to get 8 jobs.

**Comment by baconpaul** [comment]
Just checked clean checkout on windows

```
make -k -j 4 dep
make -k -j 4 dist
```

builds for me no problem

**Comment by Coirt** [comment]
`-j8` does it too, almost certain. Same speed anyway.

Fixed anyway so will close. Cheers.

**Comment by baconpaul** [comment]
Great! It might - but your dep failed looking for a target called "j8" which is why I wondered? Not sure. I've always used a space but glad it is all sorted, and hope you enjoy the modules!! Please let me know if you find anything odd or useful or fun or interesting once you have them running and thanks for getting in touch!
