### ISSUE TITLE
Rack v1: Invalid tag in plugin.json

### ISSUE THREAD

**Issue by cschol** [baconpaul/BaconPlugs#29]
From the manifest validation script:
```
Validating BaconMusic
QuantEyes: invalid tags: Quantier
```

**Comment by baconpaul** [comment]
Ok cool - easy to fix

Is there a linter I could run or something to have found this?

Thanks

**Comment by cschol** [comment]
I wrote one yesterday and will maybe add it to the library repo.

**Comment by cschol** [comment]
I wrote one yesterday and will maybe add it to the library repo.

**Comment by baconpaul** [comment]
Cool anyway I fixed this. Thanks for the good eyes!

**Comment by baconpaul** [comment]
Oh and if you are building a linter, here's 3 lines of bash that makes sure your license tag is in the SPDX list that I banged together a little while ago. Use it if you find it useful! This outputs the license if one matches a tag; and nothing if it doesn't.

```
curl -o l.json https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json
lic=`jq -r '{license} | .[]' plugin.json`
jq --arg lic "$lic" '.licenses[] | select( .licenseId==$lic )' l.json
```

**Comment by cschol** [comment]
Thanks. I came up with something similar in Python.
