### ISSUE TITLE
Bacon Plugin Collections

### ISSUE THREAD

**Issue by blackearth2014** [baconpaul/BaconPlugs#3]
Where can a newbie user download your plugins?

**Comment by cfoulc** [comment]
[BaconMusic-0.5.0-mac.zip](https://github.com/baconpaul/BaconPlugs/files/1692570/BaconMusic-0.5.0-mac.zip)

**Comment by blackearth2014** [comment]
Thanks CFoulc!!!!

**Comment by baconpaul** [comment]
Yes, thanks!

On Feb 4, 2018, at 04:19, Omar Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks CFoulc!!!!
