### ISSUE TITLE
LV BEETH pattern crashes sometimes

### ISSUE THREAD

**Issue by FrankBuss** [baconpaul/BaconPlugs#34]
When trying to move the "extra" knob after "HAMMER 4", sometimes some random characters are displayed, sometimes it crashes. Sample crash output:
```
[29.995 info src/PolyGenerator.hpp:207] loading file res/midi/beeth/(null)_2.mid
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Makefile:55: recipe for target 'run' failed
make: *** [run] Aborted
```
Tested with latest released version from the Rack site in Linux.

**Comment by baconpaul** [comment]
Oh geez sorry I must have set the upper bound wrong. Hanmer4 is the max. Thanks for the report!

**Comment by baconpaul** [comment]
Yeah so the extra goes 0-1

This line https://github.com/baconpaul/BaconPlugs/blob/94719af9406a26bdcc80c77594000ade3a308e2d/src/PolyGenerator.hpp#L226 when extra is exactly 1.0 will load beyond the end

The fix is to make that line max at nfiles- 1

**Comment by baconpaul** [comment]
OK just pushed a fix to master. Thanks for the report!

**Comment by baconpaul** [comment]
I'm traveling for a few weeks so won't get a new release of these plugs until probably later in July; so for now either build master yourself; grab the download from the releases page (which is remade automatically); or don't turn the knob all the way up :)

**Comment by FrankBuss** [comment]
No problem, I won't turn the knob all the way up :-)
How did you setup the automatic nightly build for all 3 platform? This might be useful for my plugin as well.

**Comment by baconpaul** [comment]
https://community.vcvrack.com/t/azure-pipelines-for-github-allows-build-of-plugin/2651/20
