### ISSUE TITLE
random crashes and memory corruption

### ISSUE THREAD

**Issue by FrankBuss** [baconpaul/BaconPlugs#35]
Sometimes I get NaN on some channels, if I just add the PolyGenerator module to a patch, not connected to anything:
![polygenerator](https://user-images.githubusercontent.com/1707296/59972679-d05d0900-9593-11e9-8be4-dc943f33afe1.png)
And VCV Rack crashes every 2nd or 3rd start, tested on Linux Debian. This is the patch:
[nan.vcv.zip](https://github.com/baconpaul/BaconPlugs/files/3317543/nan.vcv.zip)
I tried to run "make debug", but "bt" says "no stack trace" when trying to debug it after a crash. This is what I see in the console:
```
[0.414 info src/window.cpp:72] Loaded SVG ./res/ComponentLibrary/CKD6_0.svg
[0.414 info src/window.cpp:72] Loaded SVG ./res/ComponentLibrary/CKD6_1.svg
[0.415 info src/window.cpp:72] Loaded SVG ./plugins/Fundamental/res/LFO-1.svg
[0.415 info src/Components.hpp:517] BaconMusic loading DMP json: ./plugins/BaconMusic/res/Keypunch029.json
[0.416 info src/Components.hpp:517] BaconMusic loading DMP json: ./plugins/BaconMusic/res/Keypunch029.json
[0.416 info src/main.cpp:172] Starting engine
[0.416 info src/main.cpp:184] Running window
Makefile:55: recipe for target 'run' failed
make[1]: *** [run] Segmentation fault
```
If I remove the PolyGenerator from the patch, I can start VCV Rack a dozen times without crashing, and I never get the NaN behavior.
Tested with the latest released code of the library, not the nightly build.

**Comment by baconpaul** [comment]
Thanks for the report. I don’t see this on Mac but Mac has very forgiving uninit behavior

I’m traveling without a laptop for 2.5 weeks so won’t be able to look until mid July, apologies

**Comment by FrankBuss** [comment]
I looked closer at it, and it is not your plugin this time, sorry. I could create a coredump for the segmentation fault and then analyzed it in gdb:
```
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ff8b8c94da8 in _IO_vfprintf_internal (s=s@entry=0x7ffcfa38e500, format=<optimized out>, format@entry=0x7ff8b0354a0c "%s%d", 
    ap=ap@entry=0x7ffcfa38e668) at vfprintf.c:1637
#2  0x00007ff8b8cbbe89 in _IO_vsnprintf (string=0x7ffcfa38e5f0 "", string@entry=0x0, maxlen=<optimized out>, maxlen@entry=0, 
    format=format@entry=0x7ff8b0354a0c "%s%d", args=args@entry=0x7ffcfa38e668) at vsnprintf.c:114
#3  0x000055d282000156 in rack::string::f[abi:cxx11](char const*, ...) (format=0x7ff8b0354a0c "%s%d") at src/string.cpp:27
#4  0x00007ff8b0344820 in NoteNameField::onChange(rack::event::Change const&) () from ./plugins/Alikins/plugin.so
#5  0x00007ff8b0343caa in SpecificValueWidget::onChange(rack::event::Change const&) () from ./plugins/Alikins/plugin.so
#6  0x00007ff8b0343d44 in SpecificValueWidget::step() () from ./plugins/Alikins/plugin.so
#7  0x000055d2820696a6 in rack::widget::Widget::step (this=0x55d2834d5a70) at src/widget/Widget.cpp:151
#8  0x000055d2820696a6 in rack::widget::Widget::step (this=0x55d283505990) at src/widget/Widget.cpp:151
#9  0x000055d2820696a6 in rack::widget::Widget::step (this=0x55d283505920) at src/widget/Widget.cpp:151
#10 0x000055d2820696a6 in rack::widget::Widget::step (this=0x55d2835057d0) at src/widget/Widget.cpp:151
#11 0x000055d2820696a6 in rack::widget::Widget::step (this=this@entry=0x55d2834d7400) at src/widget/Widget.cpp:151
#12 0x000055d28202a640 in rack::ui::ScrollWidget::step (this=this@entry=0x55d2834d7400) at src/ui/ScrollWidget.cpp:36
#13 0x000055d28206445a in rack::app::RackScrollWidget::step (this=0x55d2834d7400) at src/app/RackScrollWidget.cpp:74
#14 0x000055d2820696a6 in rack::widget::Widget::step (this=this@entry=0x55d2834d7360) at src/widget/Widget.cpp:151
#15 0x000055d282048c66 in rack::app::Scene::step (this=0x55d2834d7360) at src/app/Scene.cpp:51
#16 0x000055d28201b5cc in rack::Window::run (this=0x55d2830bae60) at src/window.cpp:363
#17 0x000055d281f9dd9d in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:185
```
Furthermore after some more testing I could see the stuck channel with NaN even when your plugin is not loaded, so I guess the segmentation fault and the memory corruption is coming from the same module. Will now bother the other plugin dev :-)

**Comment by baconpaul** [comment]
Ok thanks!

**Comment by FrankBuss** [comment]
Found the crash bug:
https://github.com/alikins/Alikins-rack-plugins/issues/13
but looks like it is unrelated to the NaN bug, but I think this is a problem in the Fundamental plugin, will try to search this now.

**Comment by baconpaul** [comment]
Yeah a stress test module which took another module and sent randomness to the inputs and wiggled all the knobs and set itself up automatically with wires would be very useful. Haven’t looked st the apis enough to know how easy that is from a wiring perspective but the rest is eminently doable. 

When im back developing happy to toss in a hand if you want to do something like that in your modules
