### ISSUE TITLE
request: sound input on KarplusStrongPoly

### ISSUE THREAD

**Issue by glocke01** [baconpaul/BaconPlugs#36]
it'd be cool to have an input that allowed you to provide your own excitation input into the KarplusStrongPoly waveguide. cool modules, bro!

**Comment by baconpaul** [comment]
Oh that’s a good idea! I will add that in the next release, probably in early August. Thanks!

**Comment by baconpaul** [comment]
This is an ancient request I know, but just wanted to let you know if you re still a rack user, in the next week we will bring the urge string module to vcv rack, which was based loosely on this module, and it has an audio input. I've marked this module as hidden for a future release so am closing this issue.

But it's a good idea, and having it in surge string is an even better idea :)

**Comment by glocke01** [comment]
I am still using VCV. Thanks for all your hard work. SurgeXT is awesome, and I am very, very happy to hear that there is activity on the Surge VCV collection!

**Comment by baconpaul** [comment]
> I am still using VCV. Thanks for all your hard work. SurgeXT is awesome, and I am very, very happy to hear that there is activity on the Surge VCV collection!

If you hop into the surge discord and join the #surge-rack room you can even get a pre-beta sneak peek. Or just be patient and wait until sometime late next week. If you do show up on discord, tag me in that room and I'll explain how the string thing works....

https://discord.gg/HkwDdVGn
