### ISSUE TITLE
Baconplugs dark

### ISSUE THREAD

**Issue by Eurikon** [baconpaul/BaconPlugs#39]
Hi Paul, 
could there be a possibility that you could apply the Surge dark theme to your BaconPlugs as well?
Or variant thereof?

**Comment by baconpaul** [comment]
I hadn’t thought of it but the code isn’t dissimilar and both are gpl3 so I guess I could borrow similar ideas. I didn’t think people really used these plugs for much tbh! But happy to add this to the list for when I next open them up

**Comment by falkTX** [comment]
The commit 2bc40e3a13ad4a9d79ad327abdfe012f6b410805 adds some changes for this, but it is a compile-time option.

Screenshot for easy reference.

![Screenshot_20220126_233453](https://user-images.githubusercontent.com/1334853/151264776-1cd302fe-26b9-4dc2-bead-4edb0019fd55.png)

**Comment by baconpaul** [comment]
Hi

I'm in the process of adding a proper dark mode support, using a mechanism I cribbed from the new XT modules, which is in #71 so gonna close this.

**Comment by falkTX** [comment]
that is very appreciated. I tried to make my changes happen on runtime in your modules, but the heavy caching of GL stuff made that quite complicated and I gave up.

please do tell when finalized, would be great to integrate this with the 22.09-added Cardinal global switch for light vs dark mode (it is basically a `bool rack::settings::darkMode` global variable).
too bad VCV Rack never added an API like this...

**Comment by baconpaul** [comment]
Yeah I have added an api `baconpaul::rackplugs::BaconStyle::setStyle` which takes an enum LIGHT or DARK and updates the state accordingly. I'm sure you can hook that into whatever else you need. Right now I have it hooked to a RMB on the module and it works fine (although the style sheets aren't finished yet so some modules still look pretty wonky).

I'm also hiding many of the modules which should be deprecated anyway, just fyi.

**Comment by baconpaul** [comment]
<img width="1164" alt="Screen Shot 2022-10-28 at 9 02 34 PM" src="https://user-images.githubusercontent.com/13387561/198754796-00e39de8-548b-4f95-ab38-492b6b6de347.png">
<img width="1166" alt="Screen Shot 2022-10-28 at 9 02 40 PM" src="https://user-images.githubusercontent.com/13387561/198754798-4e655b65-7aca-4b5f-adae-a68b11c1d7cf.png">

Anyway next commit will do that

Almost ready to re-up it in the library even. A few more tweaks.

**Comment by falkTX** [comment]
oh a nice bump in art style/quality too, great to see!

**Comment by baconpaul** [comment]
its really just better colors and tighter corners on the rectangles. Oh and all the lights moved to the light layer.

And the truly crappy modules i turned off

i wrote this collection in 2017 when rack was at 0.5 and i was still sort of muddling around dsp so a lot of them aren't very good. but i want the module location for some new ideas i have now surge is getting done and i'm composing in rack a bit more.

**Comment by baconpaul** [comment]
but thanks!

anyway should be ready in a week or so.
