### ISSUE TITLE
Feature Request: PolyGnome module.

### ISSUE THREAD

**Issue by Dionisio765** [baconpaul/BaconPlugs#41]
Hi Baconpaul

Your PolyGnome module is great and very useful.
Is possible to add a start/stop button and a reset output.

Thank you and all the best.
Dionisio

**Comment by baconpaul** [comment]
Sure.
What would you want on the reset output?

**Comment by Dionisio765** [comment]
Just to reset sequencers.
I think it would very handy.
Thank you

**Comment by baconpaul** [comment]
Oh right to bring everything back in sync. Sure. Wouldn't that be an input though not an output?

**Comment by Dionisio765** [comment]
I think it is an output from PolyGnome to connect the reset input of a sequencer.
Sorry maybe i don't understand correctly.

**Comment by baconpaul** [comment]
Oh I see. So maybe I’m misunderstanding the wiring you want. What signal do you want to send to a sequencer and when? Can’t you just use a gate to do the reset on the sequencer?

Start/Stop totally makes sense of course. Both a button and a CV. As well as a reset gate input.

**Comment by Dionisio765** [comment]
Yes it could be a gate/trigger to reset the sequencer and send it when press/click the Start/Stop button.
It will be amazing.

**Comment by baconpaul** [comment]
Yup gotcha. Cool. Will take a look and see if i can get it in soon

**Comment by Dionisio765** [comment]
Hi baconpaul

Sorry for the late reply ! I´m from Portugal and witch means a big hour/time difference.
Thank you so much for your time and patience. 
All the best

**Comment by baconpaul** [comment]
Hi! I know this is an ancient request but I'm finally returning to these modules and am consolidating all the feedback on Polygnome into issue #72. Should get to it all shortly. So I'll close this issue and record the request over there.

**Comment by baconpaul** [comment]
<img width="267" alt="Screen Shot 2022-11-01 at 10 01 24 AM" src="https://user-images.githubusercontent.com/13387561/199252381-adb349f4-c32f-4c0a-8556-fb886b1b46df.png">

Here's the screenshot for the next version
