### ISSUE TITLE
CV Modulation of Freq on KarplusStrongPoly can cause module to break

### ISSUE THREAD

**Issue by mattcollier** [baconpaul/BaconPlugs#46]
Modulating the Freq to values below -5 V consistently causes the module to lock up and start producing static/noise.  I've attached a minimal example to produce the problem.

First, turn your volume down.
Turn the "Offset" knob on the attenuverter to a value below -5, -10 is a good choice.
Static should begin.
[karplus-strong.vcv.zip](https://github.com/baconpaul/BaconPlugs/files/4365472/karplus-strong.vcv.zip)

**Comment by baconpaul** [comment]
Hi!

Next week, we will release the new surge xt modules which will contain the surge string oscillator. The surge string oscillator is similar to this module as a starting point, but with many more features, so I'm moving KSPoly to hidden in bacon plugs and encouraging people to move to surge when we release it shortly.

So I'm going to close this issue. Thanks for reporting it, and please watch in rack community for an imminent announcement of the far superior surgext modules, including a string oscillator.
