### ISSUE TITLE
Proposal on PolyGnome (order of div/mult input)

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/BaconPlugs#54]
Firstly, it is a wonderful module! But the thing that drives me crazy is that the division/multiplication numbers are swapped. 

So let's say I'd like to get the 1:2 tempo of the main clock then I need to set 2 and 1 (instead of 1 and 2). Similarly if I'd like to get the 3:5 tempo of the master clock then I need to set 5 and then 3. They are the other way around! Would you please consider swapping them?

<img width="393" alt="image" src="https://user-images.githubusercontent.com/34127628/147507255-19666aa9-0b7b-4386-a5f9-b007088793b7.png">

**Comment by baconpaul** [comment]
ha funny. i guess it's just a convention but i always get confused too. I guess I could just flip the display and nothing would break since the params would be the same. I could even add a little button to do it :)

**Comment by firolightfog** [comment]
I vote for flipping! :)
Preferably no more buttons please. It looks so clean and nice this way. 
But if you happen to find some place then a RESET input would be much appreciated.

**Comment by baconpaul** [comment]
What would a "RESET" input do?

**Comment by firolightfog** [comment]
Restart from the first hit again. 

More [scientifically](https://learningmodular.com/glossary/reset/): "The Reset input on a module accepts a trigger or gate signal, and tells the module to go back the beginning of whatever it was doing. In the case of a clock divider, this means pretend the next clock is the first clock you should be counting in the division (more on that below)."

**Comment by baconpaul** [comment]
ahh cool. so basically on reset gate up, set the clock count to 0

**Comment by baconpaul** [comment]
Hi! I'm finally coming back to this set of plugins as I wrap up the new Surge XT modules, and am consolidating all the various PolyGnome requests into a single issue (#72) which I'll get to this week or next; so am closing this one as subsumed by that. Thank you

**Comment by baconpaul** [comment]
<img width="267" alt="Screen Shot 2022-11-01 at 10 01 24 AM" src="https://user-images.githubusercontent.com/13387561/199252457-6e934dde-32af-4cc4-ae7c-e283c7e3879f.png">

Here's the screenshot for the next version
