### ISSUE TITLE
Question on PolyGnome (clk cv)

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/BaconPlugs#56]
I grabbed my favorite clocks for a quick test but the CLK CV output of PolyGnome looks strange. Is it meant to double the BPM? 

<img width="507" alt="image" src="https://user-images.githubusercontent.com/34127628/147511947-a6f57007-c521-4ce3-b329-40d585077a3d.png">

**Comment by baconpaul** [comment]
Nope it's probably just wrong!

**Comment by baconpaul** [comment]
Hi! I'm finally coming back to this set of plugins as I wrap up the new Surge XT modules, and am consolidating all the various PolyGnome requests into a single issue (#72) which I'll get to this week or next; so am closing this one as subsumed by that. Thank you

**Comment by baconpaul** [comment]
<img width="267" alt="Screen Shot 2022-11-01 at 10 01 24 AM" src="https://user-images.githubusercontent.com/13387561/199252506-d1661de2-10f0-4932-b650-5582b7caf47f.png">
