### ISSUE TITLE
Proposals on PolyGnome (layout)

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/BaconPlugs#57]
Hallo Paul,

Answering one of the open tickets you carelessly mentioned "not minding one more button" on the module. So, now that Pandora's box is open :) I'd like to share my enhancement proposals for your kind consideration. 

A) Please add "hover labels" (already available in Rack v2)
<img width="179" alt="image" src="https://user-images.githubusercontent.com/34127628/147512371-8815078f-dfe7-4073-bb24-b06c2c295cee.png">

B) Please consider a GATE LENGTH knob (0%-100%) per section (even if you need to drop some text from the faceplate)
<img width="153" alt="image" src="https://user-images.githubusercontent.com/34127628/147512422-1379896b-d7e9-4cd9-bcfc-a783be7242be.png">

C) I whish I could give you an idea where to put a RUN and a RESET input socket but they're badly needed

D) I whish I could give you an idea where to put a CLK CV IN input socket (for LFO assisted jittering/swinging) but I have no clue

Cheers, Andras

**Comment by baconpaul** [comment]
Help me understand what RUN and RESET inputs would do? Thanks!

**Comment by baconpaul** [comment]
(oh and also on all of these, I'm finishing up the next surge release now, and that will take priority - especially since I can't build rack on my mac!)

**Comment by firolightfog** [comment]
Oh, I've just realized that ticket #41 has already mentioned the need for a RESET. Anyway, looking forward to any updates that may arrive. Best regards, Andras

**Comment by baconpaul** [comment]
Hi! I'm finally coming back to this set of plugins as I wrap up the new Surge XT modules, and am consolidating all the various PolyGnome requests into a single issue (#72) which I'll get to this week or next; so am closing this one as subsumed by that. Thank you

**Comment by baconpaul** [comment]
<img width="267" alt="Screen Shot 2022-11-01 at 10 01 24 AM" src="https://user-images.githubusercontent.com/13387561/199252576-17536288-187e-46dc-a47e-d4ff48dbf2c1.png">

I took all the advice here and here's the next version
