### ISSUE TITLE
Proposal Glissinator ...

### ISSUE THREAD

**Issue by ulibs66** [baconpaul/BaconPlugs#63]
Dear Paul,

afaik Glisssinator is the only plugin that can provide constant time glide (as opposed to constant rate glide). Musically this is preferable IMHO. For me it would be a real advantage to  have cv-control for the slider that controls the glide  time ...
Any chance?

very best regs, Uli Papke

**Comment by baconpaul** [comment]
You know i've been doing more rack development lately (in another project). I should return to these modules and clean them up. Thanks for the suggestion - its a good one. Will do a sweep over these issues this autumn.

**Comment by ulibs66** [comment]
That is really good news! TIA, Uli

**Comment by baconpaul** [comment]
<img width="1098" alt="Screen Shot 2022-10-28 at 8 35 28 AM" src="https://user-images.githubusercontent.com/13387561/198588244-34cdd1c1-02c5-41f2-a63a-9aed21bc1efc.png">

There you go. Now let me see if I can get GitHub making a nightly build here. If I do make that work I'll update you and close this issue.

**Comment by baconpaul** [comment]
OK I did a merge and in theory

https://github.com/baconpaul/BaconPlugs/releases/tag/Nightly

will contain a build now which has the feature. If you could test that it would be really useful to know that I've set up the build correctly (and also that the feature acts as you expect)

**Comment by ulibs66** [comment]
Dear Paul,

that was fast ...

it works nicely! 

Thank you!

**Comment by baconpaul** [comment]
Great

Yeah I went to re-do the modules today and got more done than I thought

I'll get the updated ones into the library in the next fortnight or so.

**Comment by ulibs66** [comment]
Even better news! And: I suppose FalkTX is aware of that ...

**Comment by baconpaul** [comment]
I submitted it to the library yesterday so should be there in a few days.

**Comment by ulibs66** [comment]
btw: i downloaded the surge xt for rack nightly yesterday. i just played around with the filter in a patch ... wow I dare to call that a quantum leap. Awesome work!

**Comment by baconpaul** [comment]
thank you! Yeah we've done a lot of work on surge in the last 3 years and bringing it to rack again is useful.

try the wave shapers and polyphonic fx also!
