### ISSUE TITLE
Potential leak returned after reverting crashing fix

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/BaconPlugs#67]
In 7748e55ed76e804a16b5d254c062f6e2bf0e7a8c @falkTX added cleanup to destructors for widgets which weren't added, but that causes a crash in VCV Rack Pro 2 so I reverted it

The leak is probably back though, so figure out the correct fix for the next release.

**Comment by falkTX** [comment]
might be due to GL context not being valid when some widgets are being deleted, Rack Pro is quite picky on this (while Cardinal is not).
the rest of the patch-fix should be fine though.

**Comment by baconpaul** [comment]
yeah the other two changes are fine and I kept those!

I have a correct fix for this. That code was pretty wonky and has lived too long ...

**Comment by baconpaul** [comment]
Correct fix in bfbeaf7
