### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by alto777** [baconpaul/BaconPlugs#8]
but a question.

hi Paul!

I continue to play with and study your code. I think I understand the quantizer. One simple question:
            
            if( noteF > SCALE_LENGTH-1 ) octave += 1.0;
            
line 71 in QuantEyes.cpp looks like it just can't happen. The heart of QuantEyes transplanted and watched closely doesn't trigger the octave bump no matter the contents of scaleState[].

I should have started by saying I like the functionality and display. Mostly I am thinking about quantization, trying to confirm my feeling that it isn't just what I need for some of my stuff.

alto777

**Comment by baconpaul** [comment]
Heya! Thanks for asking - I won’t get to look for a few days but I will and will let you know.

**Comment by baconpaul** [comment]
To answer your question: From looking at the code this only triggers if "root" is != 0. Here's the relevant code with comments

```
            float in = inputs[ CV_INPUT + i ].value;
            double octave, note;
            note = modf( in, &octave ); // So now octave is an integer and note is (0,1]
            float noteF = ( floor( note * SCALE_LENGTH ) + root ); 
                 // since note is (0,1] noteF is between root and SCALE_LENGTH-1+root
            int noteI = (int)noteF % SCALE_LENGTH;
                 // Thus noteI is the part in the octave (it is now between 0 and SL-1 wrapped)
            
            if( noteF > SCALE_LENGTH-1 ) octave += 1.0;
                 // but if root has pushed us over the top of the integer, we need to inc the ocrtave
```

In your stress tests, did you set the root to something other than 0?

When I get back to working on 2.6.3 I plan to do the same template trick I did in glissinator to make all the steppers testable without rack. When I do that I'll code this example up.

**Comment by baconpaul** [comment]
https://github.com/baconpaul/BaconPlugs/commit/3faf1669ebc25443a397ac353c291752169d5c20

**Comment by alto777** [comment]
Sound of hand slapping forehead. Doh!

My surgical technique needs work. I'll spare you the blow by blow and simply apologize abjectly.

It wasn't so much stress testing, but trying to be sure I understood the math, which I do, now even better. THX.

a7

**Comment by baconpaul** [comment]
No need to apologize! Thanks for looking at the modules!
