### ISSUE TITLE
PolyGnome knobs to snap

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/BaconPlugs#80]
PolyGnome has become a real beast with the recent changes. :)

Would you please consider snapping the numberator & denominator knobs to integers? 
`
paramQuantities[MYKNoBS]->snapEnabled = true;

-----

And maybe changing the range of denominators to a more common 1-32?

<img width="200" alt="image" src="https://user-images.githubusercontent.com/34127628/201460146-81756db3-0827-4cbf-8ff5-f962be33cc2f.png">

`

**Comment by baconpaul** [comment]
Oh sure. Good idea! 

I revived this as part of getting surge xt going again but didn’t do a final quality sweep. Appreciate the idea. I’ll get it in next release.

**Comment by baconpaul** [comment]
This one was super easy so I just pushed it. Should be in the nightly here in about 30 minutes. I'll get the other module I want wrapped up and this into the library soon enough also.
