### ISSUE TITLE
PolyGnome autoreset

### ISSUE THREAD

**Issue by firolightfog** [baconpaul/BaconPlugs#81]
PolyGnome currently offers a button and CV input for resetting the clock. And it's very useful and works perfectly!

Would you please consider squeezing a knob for auto-reset? (0 would mean never restart unless CV/knob input, but let's say 7 could mean that after the seventh pulse the clock is resetting.)

![image](https://user-images.githubusercontent.com/34127628/201460474-0477c3a8-6605-4b9f-a9e1-227ce9b21160.png)

**Comment by baconpaul** [comment]
Oh that’s a good idea 
And gray out the number if it is zero

**Comment by baconpaul** [comment]
oh of course, unless you are using all the clocks, you could set one clock to 1/7 and then wire its output to the reset CV. That *should* auto-reset properly (although I haven't tried it just speculating at the start of my morning).

But anyway I'll get to these and at least update the nightly. I have one other module and some other tweaks before the next sweep of these - and I gotta get Surge XT into the library too of course!

**Comment by firolightfog** [comment]
I tried self-patching... Didn't work for me.

Ugh, those XT modules are brilliant. You did a fantastic work there!

**Comment by baconpaul** [comment]
i wonder why? I'll look at that also when i add this feature

and thanks. Yeah we are really proud of XT. These bacon plugs modules are ancient and kinda in need of some love, but the recent work with proper team and stuff has turned out really well.

**Comment by baconpaul** [comment]
OK I added this in! Should be in a nightly here soon

There's one other module I want to add and a tiny bit more cleanup but I'll update the library in the next 2-3 weeks.
