### ISSUE TITLE
Source archives are old

### ISSUE THREAD

**Issue by jpnielsen** [baconpaul/BaconPlugs#85]
https://github.com/baconpaul/BaconPlugs/releases/tag/Nightly

the source .zip and tar.gz files are not up to date.

**Comment by baconpaul** [comment]
yeah i know. the GitHub actions only updates them when the tag is created. I actually have no idea how to fix that. Does it matter much?

**Comment by baconpaul** [comment]
Oh wow it was actually pretty easy to fix. Just add https://github.com/baconpaul/BaconPlugs/commit/95777e16ebfbed43f60643ab0bc3ac2d0729ac92 to the actions.
