### ISSUE TITLE
Update ci definition

### ISSUE THREAD

**Issue by qno** [baconpaul/BaconPlugs#86]
https://github.com/baconpaul/BaconPlugs/blob/22bbc5d7e32dd5abec0183b12b519f613dd06d8c/.github/workflows/build-plugin.yml#L1

Hi,

you should update the build-plugin.yml definition. Just copy the one from surge-rack, which is updated to use always the latest Rack SDK Docker container.

**Comment by baconpaul** [comment]
https://github.com/baconpaul/BaconPlugs/commit/174614071d1965ce2f21feaa64842c3f781eae22

I did that exactly 4 days ago. Is there something I missed?

**Comment by qno** [comment]
OK - I see now, it is correct. I don't know what I saw today morning.

Nevermind ...

**Comment by baconpaul** [comment]
The library version uses the old one 

by the way thank you so much for all your efforts here. Super valuable!

**Comment by qno** [comment]
Thank you, no problem.

I also need to thank you for working on the awesome Surge Rack plugin!

**Comment by baconpaul** [comment]
I literally wouldn't have started the work if you didn't help me get the make system going back in the summer. So thank you!
