### ISSUE TITLE
Why doesn't lint buddy HTML open on windows?

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/BaconPlugs#87]
open in browser wrong with a file:// probably

**Comment by david-c14** [comment]
file:// should be fine.    But you don't have a server specified, so there should be an empty section where the server goes

`file://server/path`

For windows that means that the end result might be something like:

`file:///C:/Users/Me/Documents/Rack2/BaconPaul/LintBuddy//rpt-xxx.html`

You need to end up with three slashes after the `file:`  At the moment your code is generating 2 slashes.    

--edit--

I guess that on linux and mac,  the path returned by asset::user would start with a slash.  That's *probably* not the case for windows, but it might be if your user directory is not local to the PC.    Perhaps you need to add a slash at the beginning of the path if the first character is not already a slash??

**Comment by baconpaul** [comment]
ahh right and on linux i get that for free since the first token of my path is a /. thank you

**Comment by baconpaul** [comment]
I just made this change. Thanks!
