### ISSUE TITLE
another non-issue

### ISSUE THREAD

**Issue by alto777** [baconpaul/BaconPlugs#9]
hi Paul!

I noticed the KarplusStrongPoly is now not just a blank panel, finally took your advice and built/installed your new(er) modules.

KSP - amazing! I love it. If it gets better, well, even better.

I note that a CV fed into the packet selector ends up choosing <nothing> at 10.0 volts. I don't know if this was intentional. If so maybe that should be from 9.xx and up.

I would like you to consider adding two pushbuttons:

1. an onboard trigger that would, er, trigger the module.
2. a "kill" button, perhaps with a VC input also, in the attenuate area that would cease all accumuated sounds. Perhaps gently over some milliseconds. 

Also by "beat" in your description do you mean it in the sense of "arrive sooner" thereby locking in the parameters? I did a bunch of experiments before reading the documentation (learning style thing!) and did not notice this. I will look more carefully. I was, at it happens, using two SEQ-3s with different lengths, one for frequency and one for packet select. This is when I noticed the 10.0 volt thing BTW.

At first I was reading "beat" in the heterodyne sense.

a7

**Comment by baconpaul** [comment]
All great ideas. And trigger button is one I should have thought of!! Glad you like it tho.

 By beat I meant “if you have a single seq3 and use gate to trigger and row 1 to set freq but manipulate row1 the one sample delay makes it wrong”.

So

Seq3 gate _> trigger
Seq3 row > harmonee > freq

Means the trigger arrives one sample ahead of the harmonized frequency giving the wrong result

I’ll clean up the doc as I head to 063

**Comment by alto777** [comment]
haha, "nothing" in angle brackets disappears. I meant to say nothing is selected at 10.0 therefor you get silence, which you don't get because you still get the last real choice at 9.99 volts. So if silence is to be a CV selectable packet choice it might enjoy a bit more width. Otherwise 10.0 plus should max out the knob.

**Comment by baconpaul** [comment]
Oh nice catch! Thanks.

**Comment by alto777** [comment]
Yes, thatsa fix. I wonder aloud, well in print, if the CV should actually be allowed to max out and go beyond to an Nth + 1 slot which would silence the generator?

Of course if this is what the patch required it could be done externally in as many ways as there are synthesists, so it's not a big deal feature request, but I did in fact wonder at first if this was a feature or a mistake.

Also I would say that while features are not live you might could just suppress the appearance of any non-functional affordances. Perhaps your plan is to have everything all set for the next release official release, that would certainly be my hope!

a7

**Comment by baconpaul** [comment]
Oh yeah you mean the “release one has only one filter”. Yeah I put that in since it’s an important part of the alto and I’m noodling with other filters but should have grayed it on this release. I just didn’t want to lay out the ui twice...

**Comment by baconpaul** [comment]
OK so I added both the buttons, cleaned up the documentation, add a silenceGracefully method which does that, and used a clamp rather than a min. This implements your suggestions it seems! If you grab head on branch candidate_v0.6.3 you should see them.

Thanks for the feedback! I appreciate it.
